### ISSUE TITLE
npm run build for windows on firefox, chrome and opera fails initially : TypeError: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by mbuotidem** [webcompat/webcompat-reporter-extensions#135]
npm run build for firefox, chrome and opera fail with error : 

TypeError: Cannot read property 'properties' of undefined
    at module.exports (C:\Users\Michael\webcompat-reporter-extensions\node_modules\webpack-cli\bin\config-yargs.js:89:48)
    at C:\Users\Michael\webcompat-reporter-extensions\node_modules\webpack-cli\bin\webpack.js:60:27
    at Object.<anonymous> (C:\Users\Michael\webcompat-reporter-extensions\node_modules\webpack-cli\bin\webpack.js:515:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

**Fix : Downgrade to webpack@4.19.1 if you are on 4.20. See: https://github.com/webpack/webpack/issues/8082**

![run build fails](https://user-images.githubusercontent.com/4692052/46248105-87986b00-c3da-11e8-8ac9-f634b6e72aa9.PNG)

**Comment by laghee** [comment]
[Webpack claims the problem is in the CLI](https://github.com/webpack/webpack/releases/tag/v4.20.0), so an alternate fix (which worked for me locally) seems to be upgrading `webpack-cli` to ^3.

**Comment by mbuotidem** [comment]
Yes, your fix works for me as well.
